import { NextResponse } from 'next/server';
import { buildOpenApiSpec } from '@/lib/route-registry';

/**
 * GET /openapi.json
 *
 * Auto-generated from src/lib/route-registry.js — do NOT edit this file directly.
 * To add/update an endpoint, update route-registry.js instead.
 */
export async function GET() {
  const spec = buildOpenApiSpec();

  return NextResponse.json(spec, {
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
